[{"cve_number": "DSA-3293-1", "severity": "UNKNOWN", "description": "pyjwt - security update", "score": "unknown", "cvss_version": "unknown", "cvss_vector": "unknown", "data_source": "OSV", "last_modified": "2022-08-10T07:08:25.262907Z"}]